version: "3.9"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wisingtax@123
      POSTGRES_DB: wising_tax
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./wising_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:wisingtax@123@db:5432/wising_tax
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./wising_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend

volumes:
  pg_data:
